set nocompatible
syntax on
set number
set autoread
set ruler
set ignorecase
set nobackup
set nowb
set noswapfile
set nowrap
colorscheme monokai
set cmdheight=1
set showmatch
set novisualbell
set noerrorbells
set background=dark
set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4
set scrolloff=10
