#!/bin/sh

BATTERY=$(acpi | awk '{print $4+0}')

echo $BATTERY%
echo

if [ "$BATTERY" -lt 25 ]
then
	echo "#F92672"
elif [ "$BATTERY" -lt 50 ]
then
	echo "#FD971F"
elif [ "$BATTERY" -lt 75 ]
then
	echo "#FFFF33"
else
	echo "#A6E22E"
fi
