#!/bin/sh

SIGNAL=$(iwlist wlp3s0 scan | grep Quality | awk '{print $1}' | cut -d '=' -f 2)
MAX=$(echo $SIGNAL | cut -d '/' -f 2)
CURRENT=$(echo $SIGNAL | cut -d '/' -f 1)
QUALITY=$(expr $CURRENT \* 100 / $MAX)

if [ $QUALITY -ne 0 ]
then
	echo "${QUALITY}%"
	echo
	
	if [ "$QUALITY" -lt 25 ]
	then
		echo "#F92672"
	elif [ "$QUALITY" -lt 50 ]
	then
		echo "#FD971F"
	elif [ "$QUALITY" -lt 75 ]
	then
		echo "#FFFF33"
	else
		echo "#A6E22E"
	fi
fi
